# Generated by Django 3.0.5 on 2020-11-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos1',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='datos1',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='datos1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
